name: Build Docker Images

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional: Tag to build'
        required: false
      latest:
        description: Should push latest tag
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: pmoscode/excalidraw
      SUBMODULE_PATH: excalidraw

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine latest tag in submodule
        id: submodule
        run: |
          cd "$SUBMODULE_PATH"
          git fetch --tags --quiet
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            LATEST_TAG="${{ github.event.inputs.tag }}"
            echo "Using provided tag: $LATEST_TAG"
          else
            LATEST_TAG=$(git tag --sort=-v:refname | head -n1)
            echo "Using determined tag: $LATEST_TAG"
          fi
          
          echo latest_tag=$LATEST_TAG >> $GITHUB_OUTPUT
          echo "Using tag: $LATEST_TAG"

      - name: Get current Docker Hub latest tag
        id: hub
        run: |
          HUB_TAG=$(curl -fsSL "https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags/?page_size=100" \
            | jq -r '.results[].name' | grep -E '^v?[0-9]+\.[0-9]+' | sort -Vr | head -n1 || true)
          
          echo hub_tag=$HUB_TAG >> $GITHUB_OUTPUT
          
          echo "Current tag on Docker Hub: $HUB_TAG"
          echo "Latest tag in repo: ${{ steps.submodule.outputs.latest_tag }}"

      - name: Compare versions
        id: compare
        run: |
          TAG_REPO="${{ steps.submodule.outputs.latest_tag }}"
          TAG_HUB="${{ steps.hub.outputs.hub_tag }}"
          should_build=false

          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            should_build=true
          else
            # When no tag in Docker Hub exists → build
            if [[ -z "$TAG_HUB" ]]; then
              should_build=true
            elif dpkg --compare-versions "$TAG_REPO" gt "$TAG_HUB"; then
              should_build=true
            fi
          fi

          echo should_build=$should_build >> $GITHUB_OUTPUT
          echo "Decision: should_build=$should_build"

      - name: Always build and push nightly
        run: |
          chmod +x build-images.sh
          ./build-images.sh --push --only-nightly

      - name: Conditionally build latest/tag images
        id: release
        if: steps.compare.outputs.should_build == 'true'
        run: |
          ./build-images.sh --push --only-release --tag "$TAG" 
          echo release_tag=$TAG >> $GITHUB_OUTPUT

      - name: Tag current repo with same version
        if: steps.release.outputs.release_tag != ''
        run: |
          TAG="${{ steps.release.outputs.release_tag }}"
          
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG exists. Not tagging again..."
          else
            echo "Tagging current repo with $TAG"
            
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
          
            git tag -f "$TAG"
            git push origin "$TAG" --force
          fi
